### ISSUE TITLE
计算机学院模板跟官网不一致

### ISSUE THREAD

**Issue by cqupeng** [TheNetAdmin/zjuthesis-std#2]
http://cspo-zju-edu-cn.webvpn.zju.edu.cn:8001/2021/0129/c27174a2249100/page.htm

**Comment by cqupeng** [comment]
原来跟学校的统一了

**Comment by cqupeng** [comment]
[毕业论文模板.docx](https://github.com/TheNetAdmin/zjuthesis-std/files/7315438/default.docx)

**Comment by TheNetAdmin** [comment]
这是今年计算机学院硕士模板改成了学校硕士模板吗，以前是计算机学院自己做的一个硕士模板

**Comment by cqupeng** [comment]
貌似是，我上面发的是计算机学院官网的，跟你的学校模板预览出来的差不多

**Comment by TheNetAdmin** [comment]
那我这两天把CS硕士模板的格式改回到学校模板

**Comment by TheNetAdmin** [comment]
zjuthesis v8.1.1 版本发布，包含了这里提到的 CS 硕士模板格式更新

**Comment by wanghonglie** [comment]
这是2021年1月19日发在计算机学院官网的，phd和master好像合到了一起。
[浙江大学研究生学位论文编写规则.docx](https://github.com/TheNetAdmin/zjuthesis-std/files/8087550/default.docx)
